// <auto-generated />
namespace FacSystemPropietaria.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Changefac1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changefac1));
        
        string IMigrationMetadata.Id
        {
            get { return "202104062001524_Change fac 1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
